/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controlerUI.ThemeManager;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import komunikacija.Komunikacija;
import model.CVM;
import model.Takmicenje;
import niti.Osvezi_Tabele;
import operacije.Operacije;
import transfer.Klijentski_Zahtev;
import transfer.Serverski_Odgovor;

/**
 *
 * @author Srecko
 */
public class Forma_TAKMICENJE extends javax.swing.JFrame {

    private CVM prijavljen;
    private Forma_TAKMICENJE FT;

    /**
     * Creates new form Forma_Prijava
     */
    public Forma_TAKMICENJE(CVM prijavljen) {
        this.prijavljen = prijavljen;

        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        ThemeManager.applyTheme(this);

        //prikaziPodatke();
        osveziTabele();

        Osvezi_Tabele.dodajZadatak(() -> osveziTabele());
        Osvezi_Tabele.pokreni();

        prikaziTrenutniDatumIVreme(jLabel_DatumVreme);

        jTable_PRETHODNA.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = jTable_PRETHODNA.getSelectedRow();
                if (selectedRow != -1) {
                    Takmicenje selektovano = ((Model_Tabele_Takmicenje) jTable_PRETHODNA.getModel()).getTakmicenjeAt(selectedRow);
                    Forma_Takmicenje_Detalji ftd = new Forma_Takmicenje_Detalji(selektovano, prijavljen, Forma_TAKMICENJE.this);
                    ftd.setVisible(true);
                }
            }
        });

        jTable_BUDUCA.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = jTable_BUDUCA.getSelectedRow();
                if (selectedRow != -1) {
                    Takmicenje selektovano = ((Model_Tabele_Takmicenje) jTable_BUDUCA.getModel()).getTakmicenjeAt(selectedRow);
                    Forma_Takmicenje_Detalji ftd = new Forma_Takmicenje_Detalji(selektovano, prijavljen, Forma_TAKMICENJE.this);
                    ftd.setVisible(true);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_PRETHODNA = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel_DatumVreme = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_BUDUCA = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton_Dodaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Takmičenja");

        jLabel1.setText("Datum i vreme: ");

        jLabel3.setText("Prethodna takmicenja");

        jTable_PRETHODNA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_PRETHODNA);

        jButton1.setText("Nazad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_DatumVreme.setDisplayedMnemonic('D');

        jTable_BUDUCA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_BUDUCA);

        jLabel7.setText("Predstojeca takmicenja");

        jButton_Dodaj.setText("Kreiraj novo takmicenje");
        jButton_Dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Dodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_DatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(364, 364, 364)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_DatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton_Dodaj))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_DodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DodajActionPerformed
        Forma_Takmicenje_Detalji ftd = new Forma_Takmicenje_Detalji(null, prijavljen, Forma_TAKMICENJE.this);
        ftd.setVisible(true);
    }//GEN-LAST:event_jButton_DodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Dodaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel_DatumVreme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_BUDUCA;
    private javax.swing.JTable jTable_PRETHODNA;
    // End of variables declaration//GEN-END:variables

    private void prikaziPodatke() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

//    public void osveziTabele() {
//        
//    try {
//        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_SVA_TAKMICENJA, null);
//        Komunikacija.getInstance().posalji_zahtev(kz);
//        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();
//
//        if (so != null && so.getOdgovor() instanceof List) {
//            List<Takmicenje> svaTakmicenja = (List<Takmicenje>) so.getOdgovor();
//
//            List<Takmicenje> prosla = new ArrayList<>();
//            List<Takmicenje> buduca = new ArrayList<>();
//            Date danas = new Date();
//
//            for (Takmicenje t : svaTakmicenja) {
//                if (t.getDatum().before(danas)) {
//                    prosla.add(t);
//                } else {
//                    buduca.add(t);
//                }
//            }
//
//            jTable_PRETHODNA.setModel(new Model_Tabele_Takmicenje(prosla));
//            jTable_BUDUCA.setModel(new Model_Tabele_Takmicenje(buduca));
//        }
//
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "Greška pri učitavanju takmičenja: " + e.getMessage());
//    }
//}
//    public void osveziTabele() {
//        try {
//            Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_SVA_TAKMICENJA, null);
//            Komunikacija.getInstance().posalji_zahtev(kz);
//            Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();
//
//            if (so != null && so.getOdgovor() instanceof List) {
//                List<Takmicenje> svaTakmicenja = (List<Takmicenje>) so.getOdgovor();
//
//                List<Takmicenje> prosla = new ArrayList<>();
//                List<Takmicenje> buduca = new ArrayList<>();
//                Date danas = new Date();
//
//                for (Takmicenje t : svaTakmicenja) {
//                    if (t.getDatum().before(danas)) {
//                        prosla.add(t);
//                    } else {
//                        buduca.add(t);
//                    }
//                }
//
//                jTable_PRETHODNA.setModel(new Model_Tabele_Takmicenje(prosla));
//                jTable_BUDUCA.setModel(new Model_Tabele_Takmicenje(buduca));
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Greška pri učitavanju takmičenja: " + e.getMessage());
//        }
//    }
    public void osveziTabele() {
        try {
            Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_SVA_TAKMICENJA, null);
            Komunikacija.getInstance().posalji_zahtev(kz);
            Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

            if (so != null && so.getOdgovor() instanceof List) {
                List<Takmicenje> svaTakmicenja = (List<Takmicenje>) so.getOdgovor();

                List<Takmicenje> prosla = new ArrayList<>();
                List<Takmicenje> buduca = new ArrayList<>();
                Date danas = new Date();

                for (Takmicenje t : svaTakmicenja) {
                    if (t.getDatum().before(danas)) {
                        prosla.add(t);
                    } else {
                        buduca.add(t);
                    }
                }

                jTable_PRETHODNA.setModel(new Model_Tabele_Takmicenje(prosla));
                jTable_BUDUCA.setModel(new Model_Tabele_Takmicenje(buduca));

                // Forsiraj repaint (nekad JTable ne osvezi odmah)
//            jTable_PRETHODNA.revalidate();
//            jTable_PRETHODNA.repaint();
//            jTable_BUDUCA.revalidate();
//            jTable_BUDUCA.repaint();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju takmičenja: " + e.getMessage());
        }
    }

    private void prikaziTrenutniDatumIVreme(JLabel label) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy. HH:mm:ss");

        Timer timer = new Timer(1000, e -> {
            label.setText(sdf.format(new Date()));
        });
        timer.start();
    }

}
