/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import com.sun.source.tree.IfTree;
import controlerUI.ThemeManager;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.AMKlub;
import model.Mesto;
import niti.Osvezi_Tabele;
import operacije.Operacije;
import transfer.Klijentski_Zahtev;
import transfer.Serverski_Odgovor;

/**
 *
 * @author Srecko
 */
public class Forma_AM_Klubovi extends javax.swing.JFrame {

    public static List<AMKlub> LIST_AMK = new ArrayList<>();
    public static List<Mesto> LIST_MESTO = new ArrayList<>();
    
    /**
     * Creates new form Forma_AM_Klubovi
     */
    public Forma_AM_Klubovi() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        ThemeManager.applyTheme(this);

        //jButtonAZURIRAJ.setVisible(false);
        
        PRIKAZI_PODATKE_TABELE();

        Osvezi_Tabele.dodajZadatak(() -> PRIKAZI_PODATKE_TABELE());
        Osvezi_Tabele.pokreni();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAMK = new javax.swing.JTable();
        jButtonDODAJ = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Avio Modelarski Klubovi");

        jTableAMK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAMKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAMK);

        jButtonDODAJ.setText("Dodaj");
        jButtonDODAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDODAJActionPerformed(evt);
            }
        });

        jButton3.setText("Odustani");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista svih  Avio-Modelarskih Klubova:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonDODAJ)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDODAJ)
                    .addComponent(jButton3))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTableAMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAMKMouseClicked

        int selectedRows = jTableAMK.getSelectedRow();
        if (selectedRows != -1) {
            AMKlub selektovaniAMK
                    = ((Model_Tabele_AMK) jTableAMK.getModel()).getAMKlubAt(selectedRows);

            Forma_Detalji_AMK fdamk = new Forma_Detalji_AMK(this, rootPaneCheckingEnabled, selektovaniAMK);
            fdamk.setVisible(true);
        }
    }//GEN-LAST:event_jTableAMKMouseClicked

    private void jButtonDODAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDODAJActionPerformed

        Forma_Detalji_AMK fdamk = new Forma_Detalji_AMK(this, rootPaneCheckingEnabled, null);
        fdamk.setVisible(true);

    }//GEN-LAST:event_jButtonDODAJActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDODAJ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAMK;
    // End of variables declaration//GEN-END:variables

    void osvezi_tabelu() {
        Model_Tabele_AMK mta = (Model_Tabele_AMK) jTableAMK.getModel();
        mta.osvezi_tabelu();
    }
    
    public void PRIKAZI_PODATKE_TABELE() {
    List<Object[]> listaOBJ = new ArrayList<>();

    List<AMKlub> listaAMK = new ArrayList<>();
    List<Mesto> listaMesta = new ArrayList<>();

    Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_SVE_INFO_AMK, null);
    Komunikacija.getInstance().posalji_zahtev(kz);
    Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

    if (so != null && so.getOdgovor() instanceof List) {
        listaOBJ = (List<Object[]>) so.getOdgovor();
        if (!listaOBJ.isEmpty()) {

            listaAMK = new ArrayList<>();
            listaMesta = new ArrayList<>();

            for (Object[] obj : listaOBJ) {
                AMKlub amk = (AMKlub) obj[0];
                Mesto mesto = (Mesto) obj[1];

                listaAMK.add(amk);
                listaMesta.add(mesto);
            }

            LIST_AMK = listaAMK;
            LIST_MESTO = listaMesta;

            Model_Tabele_AMK mta = new Model_Tabele_AMK(listaAMK, listaMesta);
            jTableAMK.setModel(mta);
        }

        if (listaAMK.isEmpty() || listaMesta.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Greska prilikom dobijanja podataka!", "GRESKA!", JOptionPane.ERROR_MESSAGE);
            return;
        }
    }
}


//    void PRIKAZI_PODATKE_TABELE() {
//        
//        List<Object[]> listaOBJ = new ArrayList<>();
//
//        List<AMKlub> listaAMK = new ArrayList<>();
//        List<Mesto> listaMesta = new ArrayList<>();
//
//        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_SVE_INFO_AMK, null);
//        Komunikacija.getInstance().posalji_zahtev(kz);
//        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();
//
//        if (so != null && so.getOdgovor() instanceof List) {
//
//            listaOBJ = (List<Object[]>) so.getOdgovor();
//            if (!listaOBJ.isEmpty()) {
//
//                listaAMK = new ArrayList<>();
//                listaMesta = new ArrayList<>();
//
//                for (Object[] obj : listaOBJ) {
//
//                    AMKlub amk = (AMKlub) obj[0];
//                    Mesto mesto = (Mesto) obj[1];
//
//                    listaAMK.add(amk);
//                    listaMesta.add(mesto);
//                    
//                    LIST_AMK = listaAMK;
//                    LIST_MESTO = listaMesta;
//                }
//
//                Model_Tabele_AMK mta = new Model_Tabele_AMK(listaAMK, listaMesta);
//                jTableAMK.setModel(mta);
//            }
//            if (listaAMK.isEmpty() || listaMesta.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "Greska prilikom dobijanja podataka!", "GRESKA!", JOptionPane.ERROR_MESSAGE);
//                return;
//            }
//
//        }
//    }
}
