/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

//import controller.Controller;
import controlerUI.ThemeManager;
import controlerUI.ValidatorUI;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import komunikacija.Komunikacija;
import model.CVM;
import model.VcvmCVM;
import model.VrstaCVM;
import operacije.Operacije;
import transfer.Klijentski_Zahtev;
import transfer.Serverski_Odgovor;

/**
 *
 * @author Srecko
 */
public class Forma_za_podatke_o_CVM extends javax.swing.JFrame {

    private String email;
    private String lozinka;
    private CVM prijavljen;
    private VcvmCVM staraVeza; 
    Glavna_forma gf;


    /**
     * Creates new form Forma_za_podatke_o_CVM
     */
    public Forma_za_podatke_o_CVM(CVM prijavljen, Glavna_forma gf) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.SAKRI.setVisible(false);
        this.gf = gf;
        
        ThemeManager.applyTheme(this);
        
        jLabel10.setVisible(false);
        lblErrDatumLicence.setVisible(false);
        jTextField_Licenca_DO.setVisible(false);
        

        // === VALIDACIJA POLJA ===
        ValidatorUI.validateLicenca(jTextFieldLICENCA, lblErrLicenca);
        ValidatorUI.validateTelefon(jTextFieldBR_TELEFONA, lblErrTelefon);
        ValidatorUI.validateEmail(jTextFieldEMAIL, lblErrEmail);
        ValidatorUI.validateLozinka(jPasswordFieldLOZINKA, lblErrLozinka);
        ValidatorUI.validateGrad(jTextFieldGRAD, lblErrGrad);
        ValidatorUI.validateBrojZaposlenih(jTextFieldBR_ZAPOSLENIH, lblErrBrZap);
        ValidatorUI.validateDatumOsnivanja(jTextFieldDAT_OSNIVANJA, jLabel17);
        //ValidatorUI.validateDatumLicence(jTextField_Licenca_DO, lblErrDatumLicence);

        ValidatorUI.enableAutoButtonControl(
                jButtonAZURIRAJ,
                new JTextField[]{
                    jTextFieldLICENCA,
                    jTextFieldBR_TELEFONA,
                    jTextFieldEMAIL,
                    jTextFieldGRAD,
                    jTextFieldBR_ZAPOSLENIH,
                    jTextFieldDAT_OSNIVANJA,
                    //jTextField_Licenca_DO
                },
                new JComboBox[]{jComboBoxVRSTE}
        );

        this.prijavljen = prijavljen;

        popuniFormu();
        //popuniCB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCVM = new javax.swing.JLabel();
        jButtonAZURIRAJ = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPasswordFieldLOZINKA = new javax.swing.JPasswordField();
        SAKRI = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLICENCA = new javax.swing.JTextField();
        jTextFieldBR_TELEFONA = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jTextFieldBR_ZAPOSLENIH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldDAT_OSNIVANJA = new javax.swing.JTextField();
        jTextField_Licenca_DO = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldGRAD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxVRSTE = new javax.swing.JComboBox<>();
        PRIKAZI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldEMAIL = new javax.swing.JTextField();
        lblErrLicenca = new javax.swing.JLabel();
        lblErrTelefon = new javax.swing.JLabel();
        lblErrEmail = new javax.swing.JLabel();
        lblErrBrZap = new javax.swing.JLabel();
        lblErrDatumLicence = new javax.swing.JLabel();
        lblErrGrad = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblErrLozinka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CVM ");

        jLabelCVM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelCVM.setText("Osnovne invormacije: ");

        jButtonAZURIRAJ.setText("Azuriraj");
        jButtonAZURIRAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAZURIRAJActionPerformed(evt);
            }
        });

        jButton2.setText("Odustani");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordFieldLOZINKA.setText("jPasswordField1");
        jPanel1.add(jPasswordFieldLOZINKA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 240, -1));

        SAKRI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/eye_hide.png"))); // NOI18N
        SAKRI.setPreferredSize(new java.awt.Dimension(30, 30));
        SAKRI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SAKRIMousePressed(evt);
            }
        });
        jPanel1.add(SAKRI, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 20, -1));

        jLabel4.setText("Email: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel3.setText("Broj telefona:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));
        jPanel1.add(jTextFieldLICENCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, -1));
        jPanel1.add(jTextFieldBR_TELEFONA, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 240, -1));

        jLabelID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelID.setText("ID");
        jPanel1.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));
        jPanel1.add(jTextFieldBR_ZAPOSLENIH, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 240, -1));

        jLabel7.setText("Lozinka");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel10.setText("Istek licence");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel12.setText("Datum osnivanja");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, -1, -1));
        jPanel1.add(jTextFieldDAT_OSNIVANJA, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 240, -1));
        jPanel1.add(jTextField_Licenca_DO, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 240, -1));

        jLabel11.setText("Grad");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));
        jPanel1.add(jTextFieldGRAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 240, -1));

        jLabel9.setText("Broj zaposlenih");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel2.setText("Licenca: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanel1.add(jComboBoxVRSTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 240, -1));

        PRIKAZI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/eye.png"))); // NOI18N
        PRIKAZI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRIKAZIMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PRIKAZIMousePressed(evt);
            }
        });
        jPanel1.add(PRIKAZI, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel1.setText("Vrsta CVMa");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 64, -1));
        jPanel1.add(jTextFieldEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 240, -1));
        jPanel1.add(lblErrLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 260, 40));
        jPanel1.add(lblErrTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 260, 40));
        jPanel1.add(lblErrEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 290, 39));
        jPanel1.add(lblErrBrZap, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 310, 40));
        jPanel1.add(lblErrDatumLicence, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 310, 30));
        jPanel1.add(lblErrGrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 310, 40));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 310, 40));
        jPanel1.add(lblErrLozinka, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelCVM))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jButtonAZURIRAJ)
                        .addGap(108, 108, 108)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelCVM)
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAZURIRAJ)
                    .addComponent(jButton2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    
    // JOptionPane.showMessageDialog(this, "Sistem ne moze da azurira izmene", "Upozorenje", JOptionPane.WARNING_MESSAGE);
    private void PRIKAZIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRIKAZIMouseClicked

    }//GEN-LAST:event_PRIKAZIMouseClicked

    private void PRIKAZIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRIKAZIMousePressed

        SAKRI.setVisible(true);
        PRIKAZI.setVisible(false);
        String lozinka = String.valueOf(jPasswordFieldLOZINKA.getPassword());

        jPasswordFieldLOZINKA.setEchoChar((char) 0);
    }//GEN-LAST:event_PRIKAZIMousePressed

    private void SAKRIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAKRIMousePressed

        SAKRI.setVisible(false);
        PRIKAZI.setVisible(true);
        String lozinka = String.valueOf(jPasswordFieldLOZINKA.getPassword());

        jPasswordFieldLOZINKA.setEchoChar('*');
    }//GEN-LAST:event_SAKRIMousePressed

    private void jButtonAZURIRAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAZURIRAJActionPerformed

        try {
            // ---  Pokupi sve podatke iz polja ---
            int idCVM = Integer.parseInt(jLabelID.getText());
            String nazivCVM = jLabelCVM.getText();
            String licenca = jTextFieldLICENCA.getText();
            String brojTelefona = jTextFieldBR_TELEFONA.getText();
            String email = jTextFieldEMAIL.getText();
            String lozinka = new String(jPasswordFieldLOZINKA.getPassword());
            String grad = jTextFieldGRAD.getText();
            int brojZaposlenih = Integer.parseInt(jTextFieldBR_ZAPOSLENIH.getText());

            // ---  Datumi (koristimo pomocnu metodu) ---
            java.sql.Date datumOsnivanja = null;
            java.sql.Date licencaDo = null;

            if (!jTextFieldDAT_OSNIVANJA.getText().trim().isEmpty()) {
                java.util.Date parsed = parseDatumFlex(jTextFieldDAT_OSNIVANJA.getText().trim());
                datumOsnivanja = new java.sql.Date(parsed.getTime());
            }

            if (!jTextField_Licenca_DO.getText().trim().isEmpty()) {
                java.util.Date parsed = parseDatumFlex(jTextField_Licenca_DO.getText().trim());
                licencaDo = new java.sql.Date(parsed.getTime());
            }

            //
            CVM cvm = new CVM(idCVM, licenca, nazivCVM, brojTelefona, email, lozinka, grad, brojZaposlenih, datumOsnivanja);

            // 
            VrstaCVM izabranaVrsta = (VrstaCVM) jComboBoxVRSTE.getSelectedItem();

            // ---  Ažuriraj osnovne podatke ---
            Klijentski_Zahtev kz1 = new Klijentski_Zahtev(Operacije.AZURIRAJ_CVM, cvm);
            Komunikacija.getInstance().posalji_zahtev(kz1);
            Serverski_Odgovor so1 = Komunikacija.getInstance().primi_odgovor();

            if (so1 != null && "USPEH!".equals(so1.getOdgovor())) {
                // ---  Ayuriraj vezu ako postoji izabrana vrsta ---
                if (izabranaVrsta != null) {
                    VcvmCVM veza = new VcvmCVM(cvm, izabranaVrsta, licencaDo);
                    Klijentski_Zahtev kz2 = new Klijentski_Zahtev(Operacije.AZURIRAJ_VEZU, veza);
                    Komunikacija.getInstance().posalji_zahtev(kz2);
                    Serverski_Odgovor so2 = Komunikacija.getInstance().primi_odgovor();

                    if (so2 != null && "USPEH!".equals(so2.getOdgovor())) {
                        JOptionPane.showMessageDialog(this, "Podaci su uspešno ažurirani!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "CVM je ažuriran, ali veza sa vrstom nije!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Podaci su uspešno ažurirani!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Greška pri ažuriranju CVM podataka!", "Greška", JOptionPane.ERROR_MESSAGE);
            }

        } catch (ParseException pe) {
            JOptionPane.showMessageDialog(this,
                    "Greška pri unosu datuma!\nPodržani formati su: dd.MM.yyyy, dd/MM/yyyy, yyyy-MM-dd itd.",
                    "Neispravan datum", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Neispravan unos: " + e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
        }
        
        gf.popuniFormu();

//        try {
//            // --- 1. Pokupi sve podatke iz polja ---
//            int idCVM = Integer.parseInt(jLabelID.getText());
//            String nazivCVM = jLabelCVM.getText();
//            String licenca = jTextFieldLICENCA.getText();
//            String brojTelefona = jTextFieldBR_TELEFONA.getText();
//            String email = jTextFieldEMAIL.getText();
//            String lozinka = new String(jPasswordFieldLOZINKA.getPassword());
//            String grad = jTextFieldGRAD.getText();
//            int brojZaposlenih = Integer.parseInt(jTextFieldBR_ZAPOSLENIH.getText());
//
//            // --- 2. Datumi ---
//            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
//            java.sql.Date datumOsnivanja = null;
//            java.sql.Date licencaDo = null;
//
//            if (!jTextFieldDAT_OSNIVANJA.getText().trim().isEmpty()) {
//                java.util.Date datumOsnivanjaUtil = sdf.parse(jTextFieldDAT_OSNIVANJA.getText());
//                datumOsnivanja = new java.sql.Date(datumOsnivanjaUtil.getTime());
//            }
//            if (!jTextField_Licenca_DO.getText().trim().isEmpty()) {
//                java.util.Date licencaDoUtil = sdf.parse(jTextField_Licenca_DO.getText());
//                licencaDo = new java.sql.Date(licencaDoUtil.getTime());
//            }
//
//            // --- 3. CVM objekat ---
//            CVM cvm = new CVM(idCVM, licenca, nazivCVM, brojTelefona, email, lozinka, grad, brojZaposlenih, datumOsnivanja);
//
//            System.out.println("DEBUG FORMA: id=" + idCVM + ", naziv=" + nazivCVM);
//
//            // --- 4. Vrsta iz ComboBox-a ---
//            VrstaCVM izabranaVrsta = (VrstaCVM) jComboBoxVRSTE.getSelectedItem();
//
//            // --- prvo ažuriraš osnovni CVM ---
//            Klijentski_Zahtev kz1 = new Klijentski_Zahtev(Operacije.AZURIRAJ_CVM, cvm);
//            Komunikacija.getInstance().posalji_zahtev(kz1);
//            Serverski_Odgovor so1 = Komunikacija.getInstance().primi_odgovor();
//
//            if (so1 != null && so1.getOdgovor().equals("USPEH!")) {
//                if (izabranaVrsta != null) {
//                    VcvmCVM veza = new VcvmCVM(cvm, izabranaVrsta, licencaDo);
//
//                    Klijentski_Zahtev kz2 = new Klijentski_Zahtev(Operacije.AZURIRAJ_VEZU, veza);
//                    Komunikacija.getInstance().posalji_zahtev(kz2);
//                    Serverski_Odgovor so2 = Komunikacija.getInstance().primi_odgovor();
//
//                    if (so2 != null && so2.getOdgovor().equals("USPEH!")) {
//                        JOptionPane.showMessageDialog(this, "Podaci su uspešno ažurirani!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
//                        this.dispose();
//                    } else {
//                        JOptionPane.showMessageDialog(this, "CVM je ažuriran, ali veza sa vrstom nije!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
//                    }
//                } else {
//                    JOptionPane.showMessageDialog(this, "Podaci su uspešno ažurirani!", "Uspeh", JOptionPane.INFORMATION_MESSAGE);
//                    this.dispose();
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Greška pri ažuriranju CVM podataka!", "Greška", JOptionPane.ERROR_MESSAGE);
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(this, "Neispravan unos: " + e.getMessage(), "Greška", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_jButtonAZURIRAJActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PRIKAZI;
    private javax.swing.JLabel SAKRI;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAZURIRAJ;
    private javax.swing.JComboBox<VrstaCVM> jComboBoxVRSTE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCVM;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldLOZINKA;
    private javax.swing.JTextField jTextFieldBR_TELEFONA;
    private javax.swing.JTextField jTextFieldBR_ZAPOSLENIH;
    private javax.swing.JTextField jTextFieldDAT_OSNIVANJA;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JTextField jTextFieldGRAD;
    private javax.swing.JTextField jTextFieldLICENCA;
    private javax.swing.JTextField jTextField_Licenca_DO;
    private javax.swing.JLabel lblErrBrZap;
    private javax.swing.JLabel lblErrDatumLicence;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrGrad;
    private javax.swing.JLabel lblErrLicenca;
    private javax.swing.JLabel lblErrLozinka;
    private javax.swing.JLabel lblErrTelefon;
    // End of variables declaration//GEN-END:variables

    private void popuniFormu() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        // --- povuci sve podatke iz baze preko veze ---
        int id = prijavljen.getIdCVM();

        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_SVE_PODATKE_CVM_VRSTA, id);
        Komunikacija.getInstance().posalji_zahtev(kz);
        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        if (so != null && so.getOdgovor() instanceof List) {
            List<VcvmCVM> podaci = (List<VcvmCVM>) so.getOdgovor();
            if (!podaci.isEmpty()) {
                VcvmCVM prvi = podaci.get(0);

                // ⚡ osveži prijavljenog CVM iz baze
                this.prijavljen = prvi.getCvm();

                // --- osnovni podaci ---
                jLabelID.setText(String.valueOf(prijavljen.getIdCVM()));
                jLabelCVM.setText(prijavljen.getNazivCVM());
                jTextFieldLICENCA.setText(prijavljen.getLicenca());
                jTextFieldBR_TELEFONA.setText(prijavljen.getBr_telefona());
                jTextFieldEMAIL.setText(prijavljen.getEmail());
                jPasswordFieldLOZINKA.setText(prijavljen.getLozinka());
                jTextFieldGRAD.setText(prijavljen.getGrad());
                jTextFieldBR_ZAPOSLENIH.setText(String.valueOf(prijavljen.getBrojZaposlenih()));

                if (prijavljen.getDatumOsnivanja() != null) {
                    jTextFieldDAT_OSNIVANJA.setText(sdf.format(prijavljen.getDatumOsnivanja()));
                } else {
                    jTextFieldDAT_OSNIVANJA.setText("");
                }

                // --- podaci iz veze (licenca važi do) ---
                if (prvi.getLicencaVaziOd() != null) {
                    jTextField_Licenca_DO.setText(sdf.format(prvi.getLicencaVaziOd()));
                } else {
                    jTextField_Licenca_DO.setText("");
                }

                // --- popuni ComboBox sa vrstom ---
                popuniCB(prvi.getVrsta());

            } else {
                // nema veze → polja za vezu prazna, ali osveži CB
                jTextField_Licenca_DO.setText("");
                popuniCB(null);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Greška pri učitavanju podataka o CVM! \n"
                    + "Proverite konekciju sa SERVEROM!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void popuniCB(VrstaCVM trenutna) {
        jComboBoxVRSTE.removeAllItems();

        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_SVE_VRSTE_CVM, null);
        Komunikacija.getInstance().posalji_zahtev(kz);
        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        if (so != null && so.getOdgovor() instanceof List) {
            List<VrstaCVM> vrste = (List<VrstaCVM>) so.getOdgovor();
            for (VrstaCVM v : vrste) {
                jComboBoxVRSTE.addItem(v);
            }

            if (trenutna != null) {
                for (int i = 0; i < jComboBoxVRSTE.getItemCount(); i++) {
                    VrstaCVM item = (VrstaCVM) jComboBoxVRSTE.getItemAt(i);
                    if (item != null && item.getIdVrstaCVM() == trenutna.getIdVrstaCVM()) {
                        jComboBoxVRSTE.setSelectedItem(item);
                        break;
                    }
                }
            } else {
                // Ako nema vrste za taj CVM → ostaje prazno (null)
                jComboBoxVRSTE.setSelectedIndex(-1);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Greška prilikom učitavanja vrsta CVM!", "Greška", JOptionPane.ERROR_MESSAGE);
        }
    }

    private java.util.Date parseDatumFlex(String dateStr) throws ParseException {
        String[] formati = {
            "dd.MM.yyyy",
            "dd.MM.yyyy.",
            "dd/MM/yyyy",
            "dd-MM-yyyy",
            "yyyy-MM-dd",
            "d.M.yyyy",
            "dd. MM. yyyy."
        };

        for (String format : formati) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat(format);
                sdf.setLenient(false);
                return sdf.parse(dateStr);
            } catch (ParseException ignored) {
            }
        }

        throw new ParseException("Nepoznat format datuma: " + dateStr, 0);
    }

    // BLA BLA   KLASA CVMDrzava    bla bla
//    private void popuni_CB() {
//        try {
//            // Kreiranje instance klase Drzava
//            Drzava drz = new Drzava();
//
//            // Kreiranje klijentskog zahteva za popunjavanje ComboBox-a
//            Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.POPUNI_CB, drz);
//            Komunikacija.getInstance().posalji_zahtev(kz);
//
//            // Čekamo odgovor sa servera
//            Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();
//
//            // Slanje zahteva i preuzimanje liste svih država
//            List<Drzava> sveDrzave = (List<Drzava>) so.getOdgovor();
//
//            // Popunjavanje ComboBox-a sa dobijenim podacima
//            for (Drzava d : sveDrzave) {
//                jComboBoxDRZAVE.addItem(d.getNazivDrzave());
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Greška prilikom preuzimanja lista država: " + e.getMessage());
//        }
//    }
//    private void popuni_CB(String drzavaCVM) {
//        try {
//            // Kreiranje instance klase Drzava
//            VrstaCVM drz = new VrstaCVM();
//
//            // Kreiranje klijentskog zahteva za popunjavanje ComboBox-a
//            Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.POPUNI_CB_DRZAVE, drz);
//            Komunikacija.getInstance().posalji_zahtev(kz);
//
//            // Čekamo odgovor sa servera
//            Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();
//
//            // Slanje zahteva i preuzimanje liste svih država
//            List<VrstaCVM> sveDrzave = (List<VrstaCVM>) so.getOdgovor();
//
//            // Prvo dodajemo državu povezanu sa CVM-om na vrh ComboBox-a
//            jComboBoxDRZAVE.addItem(drzavaCVM);
//
//            // Zatim dodajemo ostale države osim već dodate države
//            for (VrstaCVM d : sveDrzave) {
//                if (!d.getNazivDrzave().equals(drzavaCVM)) {
//                    jComboBoxDRZAVE.addItem(d.getNazivDrzave());
//                }
//            }
//
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Greška prilikom preuzimanja lista država: " + e.getMessage());
//        }
//    }
}
