/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

//import controller.Controller;
import controlerUI.ValidatorUI;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import komunikacija.Komunikacija;
import model.CVM;
import operacije.Operacije;
import pomocne.Pomocne;
import transfer.Klijentski_Zahtev;
import transfer.Serverski_Odgovor;

/**
 *
 * @author Srecko
 */
public class Forma_za_registraciju extends javax.swing.JFrame {

    /**
     * Creates new form Forma_za_registraciju
     */
    public Forma_za_registraciju() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // === Validacija polja ===
        ValidatorUI.validateNaziv(jTextFieldNAZIV_CVM, lblErrorNaziv);
        ValidatorUI.validateLicenca(jTextFieldLICENCA, lblErrorLicenca);
        ValidatorUI.validateTelefon(jTextFieldBR_TEL, lblErrorTelefon);
        ValidatorUI.validateEmail(jTextFieldEMAIL, lblErrorEmail);

// === Automatska kontrola dugmeta ===
        ValidatorUI.enableAutoButtonControl(
                jButtonNASTAVI,
                new JTextField[]{jTextFieldNAZIV_CVM, jTextFieldLICENCA, jTextFieldBR_TEL, jTextFieldEMAIL},
                new JComboBox[]{} // nema combo boxeva
        );
        ValidatorUI.updateButtonState(jButtonNASTAVI,
                new JTextField[]{jTextFieldNAZIV_CVM, jTextFieldLICENCA, jTextFieldBR_TEL, jTextFieldEMAIL},
                new JComboBox[]{});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonNASTAVI = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEMAIL = new javax.swing.JTextField();
        jTextFieldNAZIV_CVM = new javax.swing.JTextField();
        jTextFieldLICENCA = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        jTextFieldBR_TEL = new javax.swing.JTextField();
        lblErrorNaziv = new javax.swing.JLabel();
        lblErrorLicenca = new javax.swing.JLabel();
        lblErrorTelefon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registracija");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNASTAVI.setText("Nastavi");
        jButtonNASTAVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNASTAVIActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNASTAVI, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        jLabel4.setText("Licenca");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTRACIJA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 361, -1));

        jLabel5.setText("Broj telefona");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));
        jPanel1.add(jTextFieldEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 226, -1));
        jPanel1.add(jTextFieldNAZIV_CVM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 226, -1));
        jPanel1.add(jTextFieldLICENCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 226, -1));

        jLabel1.setText("Naziv CVM-a");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));
        jPanel1.add(lblErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 300, 30));
        jPanel1.add(jTextFieldBR_TEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 226, -1));
        jPanel1.add(lblErrorNaziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 300, 40));
        jPanel1.add(lblErrorLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 300, 40));
        jPanel1.add(lblErrorTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNASTAVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNASTAVIActionPerformed

        String nazivCVM = jTextFieldNAZIV_CVM.getText();
        String licenca = jTextFieldLICENCA.getText();
        String brTel = jTextFieldBR_TEL.getText();
        String email = jTextFieldEMAIL.getText();

        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da su ovo Vasi podaci? \n"
                + "Naziv CVM-a: " + nazivCVM + "\n"
                + "Licenca: " + licenca + "\n"
                + "Broj telefona: " + brTel + "\n"
                + "Email: " + email + "\n", "Proverite podatke", JOptionPane.YES_NO_OPTION);

        if (opcija == 1) {
            JOptionPane.showMessageDialog(this, "Ispravite Vase podatke", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Lozinka se ne postavlja, server će je generisati
        CVM cvm = new CVM(0, licenca, nazivCVM, brTel, email, null, null, 0, null);

        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.REGISTRACIJA, cvm);
        Komunikacija.getInstance().posalji_zahtev(kz);

        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        if (so == null) {
            JOptionPane.showMessageDialog(this, "Greška u komunikaciji sa serverom!", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }

// NOVO:
        if (so.getOdgovor().equals("EMAIL_POSTOJI")) {
            JOptionPane.showMessageDialog(this,
                    "Korisnik sa ovim e-mailom već postoji!\n"
                    + "Prijavite se ili koristite drugu adresu.",
                    "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        // dzabe muke i truda kad nemere
//        if (so.getOdgovor().equals("GRESKA_EMAIL")) {
//            JOptionPane.showMessageDialog(this,
//                    "Registracija je uspešna, ali e-mail nije mogao biti poslat!\n"
//                    + "Proverite da li je adresa ispravna ili kontaktirajte podršku.",
//                    "Greška pri slanju e-maila", JOptionPane.WARNING_MESSAGE);
//            return;
//        }

        if (so != null && so.getOdgovor().equals("USPEH!")) {
            JOptionPane.showMessageDialog(this, "Uspesno registrovanje", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);

            // UZIMA SE NA PROVERU SIFRA KOJU KORISNIK UNOSI
            String uneta_sifra = JOptionPane.showInputDialog(this, "Unesite privremenu lozinku koja je poslata na Vasu E-mail adresu: " + email, "Provera lozinke", JOptionPane.INFORMATION_MESSAGE);

            // PROVERAVA IZ BAZE ISPRAVNOST SIFRE
            kz = new Klijentski_Zahtev(Operacije.PRIJAVA, new CVM(0, licenca, nazivCVM, brTel, email, uneta_sifra, null, 0, null));
            Komunikacija.getInstance().posalji_zahtev(kz);
            so = Komunikacija.getInstance().primi_odgovor();

            if (so != null && so.getOdgovor() instanceof CVM) {
                CVM prijavljen = (CVM) so.getOdgovor();
                JOptionPane.showMessageDialog(this,
                        "Cestitamo, samo korak Vas deli od pristupanja aplikaciji!\n"
                        + "Prijavite se sa Vasom E-mail adresom i trenutnom lozinkom.\n"
                        + "Preporucujemo da odmah promenite lozinku nakon prvog logina.",
                        "USPESNO!", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Niste uneli ispravnu privremenu lozinku, probajte opet!",
                        "GRESKA", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Desila se greska pri registrovanju, probajte ponovo!\n"
                    + "Takodje proverite konekciju sa SERVEROM!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        /*
        String nazivCVM = jTextFieldNAZIV_CVM.getText();
        String licenca = jTextFieldLICENCA.getText();
        String brTel = jTextFieldBR_TEL.getText();
        String email = jTextFieldEMAIL.getText();

        String generisana_sifra = Pomocne.generateTemporaryPassword();

// PROVERA DA LI JE KORISNIK UNEO SVOJE PODATKE PRAVILNO
        int opcija = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da su ovo Vasi podaci? \n"
                + "Naziv CVM-a: " + nazivCVM + "\n"
                + "Licenca: " + licenca + "\n"
                + "Broj telefona: " + brTel + "\n"
                + "Email: " + email + "\n", "Proverite podatke", JOptionPane.YES_NO_OPTION);
// AKO NIJE
        if (opcija == 1) {
            JOptionPane.showMessageDialog(this, "Ispravite Vase podatke", "Upozorenje!", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // SALJE MU SE MEJL SA SIFROM
        Pomocne.posalji_Email(email, generisana_sifra);

        boolean upisan = Controller.getInstance().dodaj_CVM(nazivCVM, licenca, brTel, email, generisana_sifra);

// PROVERAVAMO DA LI SE DOBRO UNELO U BAZU
        if (!upisan) {
            JOptionPane.showMessageDialog(this, "Desila se greska pri registrovanju, probajte ponovo!", "GRESKA", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        else {

// UZIMA SE NA PROVERU SIFRA KOJU KORISNIK UNOSI
            String uneta_sifra = JOptionPane.showInputDialog(this, "Uspesno registrovanje \n"
                    + "Unesite privremenu lozinku koja je poslata na Vasu E-mail adresu: " + email + " da bi ste nastavili.", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(uneta_sifra);

// PROVERAVA IZ BAZE ISPRAVNOST SIFRE
            boolean ispravna_lozinka = Controller.getInstance().login(email, uneta_sifra);

// AKO JE NEISPRAVNA 
            if (!ispravna_lozinka) {
                JOptionPane.showMessageDialog(this, "Niste uneli ispravnu privremenu lozinku, probajte opet!", "GRESKA", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, "Cestitamo, samo korak Vas deli od pristupanja aplikaciji! \n"
                    + "Prijavite se sa Vasom E-mail adresom i trenutnom lozinkom! \n"
                    + "Preporucujemo Vam da odmah promenite lozinku nakon prvog prijavljivanja sa privremenom lozinkom \n", "USPESNO!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonNASTAVIActionPerformed
*/

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNASTAVI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBR_TEL;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JTextField jTextFieldLICENCA;
    private javax.swing.JTextField jTextFieldNAZIV_CVM;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorLicenca;
    private javax.swing.JLabel lblErrorNaziv;
    private javax.swing.JLabel lblErrorTelefon;
    // End of variables declaration//GEN-END:variables
}
