/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import controlerUI.ThemeManager;
import controlerUI.ValidatorUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import komunikacija.Komunikacija;
import model.AMKlub;
import model.Mesto;
import operacije.Operacije;
import transfer.Klijentski_Zahtev;
import transfer.Serverski_Odgovor;

/**
 *
 * @author Srecko
 */
public class Forma_Detalji_AMK extends javax.swing.JDialog {

    private AMKlub amk;
    private List<AMKlub> listaAMK;
    private List<Mesto> listaMesta;

    private Forma_AM_Klubovi famk;

    private int mestoID = 0;

    /**
     * Creates new form Forma_Detalji_AMK
     */
    public Forma_Detalji_AMK(java.awt.Frame parent, boolean modal, AMKlub amk) {
        super(parent, modal);
        this.amk = amk;
        this.famk = (Forma_AM_Klubovi) parent;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        ThemeManager.applyTheme(this);

        // === VALIDACIJA POLJA ===
        ValidatorUI.validateNaziv(jTextFieldNAZIV, lblErrNaziv);
        ValidatorUI.validateTelefon(jTextFieldTLEFON, lblErrTelefon);
        ValidatorUI.validateEmail(jTextFieldEMAIL, lblErrEmail);

// === POSTAVI name atribute radi prepoznavanja (nije obavezno, ali je čisto) ===
        jTextFieldNAZIV.setName("naziv");
        jTextFieldTLEFON.setName("telefon");
        jTextFieldEMAIL.setName("email");

// === AUTOMATSKA KONTROLA DUGMETA DODAJ ===
        ValidatorUI.enableAutoButtonControl(
                jButtonDODAJ,
                new JTextField[]{jTextFieldNAZIV, jTextFieldTLEFON, jTextFieldEMAIL},
                new JComboBox[]{jComboBoxMESTA}
        );
        ValidatorUI.updateButtonState(
                jButtonDODAJ,
                new JTextField[]{jTextFieldNAZIV, jTextFieldTLEFON, jTextFieldEMAIL},
                new JComboBox[]{jComboBoxMESTA}
        );

// === AUTOMATSKA KONTROLA DUGMETA AZURIRAJ ===
        ValidatorUI.enableAutoButtonControl(
                jButtonAZURIRAJ,
                new JTextField[]{jTextFieldNAZIV, jTextFieldTLEFON, jTextFieldEMAIL},
                new JComboBox[]{jComboBoxMESTA}
        );
        ValidatorUI.updateButtonState(
                jButtonAZURIRAJ,
                new JTextField[]{jTextFieldNAZIV, jTextFieldTLEFON, jTextFieldEMAIL},
                new JComboBox[]{jComboBoxMESTA}
        );

        jButtonDODAJ.setVisible(false);

        popuniCB_mesto();

        jComboBoxMESTA.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                azurirajPodatkeCB_mesto();
            }
        });

        if (amk == null) {
            pripremiZaNoviUnos_AMK();
        } else {
            prikaziPodatkeAMK();
            postaviPocetnuVrednostCB();
        }

    }
//JOptionPane.showMessageDialog(this, "Sistem ne moze da sacuva AM Klub", "Upozorenje", JOptionPane.WARNING_MESSAGE);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNAZIV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTLEFON = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEMAIL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxMESTA = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButtonAZURIRAJ = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonOBRISI = new javax.swing.JButton();
        jButtonDODAJ = new javax.swing.JButton();
        lblErrEmail = new javax.swing.JLabel();
        lblErrNaziv = new javax.swing.JLabel();
        lblErrTelefon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Podaci o Avio Modelarskom Klubu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ID ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 87, -1, -1));

        jLabelID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelID.setText("ID");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 87, -1, -1));

        jLabel2.setText("Naziv:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        getContentPane().add(jTextFieldNAZIV, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 198, -1));

        jLabel3.setText("Broj telefona:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        getContentPane().add(jTextFieldTLEFON, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 198, -1));

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));
        getContentPane().add(jTextFieldEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 198, -1));

        jLabel5.setText("Mesto:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        getContentPane().add(jComboBoxMESTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 198, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Podaci o Avio modelarskom klubu:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 21, -1, -1));

        jButtonAZURIRAJ.setText("Azuriraj");
        jButtonAZURIRAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAZURIRAJActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAZURIRAJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 387, -1, -1));

        jButton1.setText("Odustani");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 387, -1, -1));

        jButtonOBRISI.setText("Obrisi");
        jButtonOBRISI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOBRISIActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOBRISI, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 387, -1, -1));

        jButtonDODAJ.setText("Dodaj");
        jButtonDODAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDODAJActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDODAJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 387, -1, -1));
        getContentPane().add(lblErrEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 250, 30));
        getContentPane().add(lblErrNaziv, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 200, 40));
        getContentPane().add(lblErrTelefon, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 200, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonDODAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDODAJActionPerformed

        int IDamk = vrati_id_amk() + 1;

        String naziv = jTextFieldNAZIV.getText();
        String tel = jTextFieldTLEFON.getText();
        String email = jTextFieldEMAIL.getText();
        
        if (jComboBoxMESTA.getSelectedIndex() == -1 || jComboBoxMESTA.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this,
                        "Morate odabrati opciju iz padajućeg menija!",
                        "Greška",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

        //System.out.println("MESTO: " + mestoID);
        AMKlub amk = new AMKlub(IDamk, naziv, tel, email, mestoID);

        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.DODAJ_AMK, amk);
        Komunikacija.getInstance().posalji_zahtev(kz);
        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        if (so == null || so.getOdgovor().equals("NEUSPEH!")) {

            JOptionPane.showMessageDialog(this, "Greska prilikom dodavanja AM kluba u bazu!\n"
                    + "Proverite da li ste upisali vrednosti u sva polja i odabrali mesto iz padajuceg menija \n"
                    + "Takodje proverite konekciju sa BAZOM!", "GRESKA!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(this, "Uspesno dodavanje AM kluba u bazu!", "USPEH!", JOptionPane.INFORMATION_MESSAGE);
        famk.PRIKAZI_PODATKE_TABELE();
        this.dispose();

    }//GEN-LAST:event_jButtonDODAJActionPerformed

    private void jButtonAZURIRAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAZURIRAJActionPerformed

        int id = Integer.valueOf(jLabelID.getText());
        String naziv = jTextFieldNAZIV.getText();
        String telefon = jTextFieldTLEFON.getText();
        String mejl = jTextFieldEMAIL.getText();

        // uzmi selektovani index iz CB i preko liste dohvatimo pravi ID
        int index = jComboBoxMESTA.getSelectedIndex();
        if (index >= 0 && index < listaMesta.size()) {
            mestoID = listaMesta.get(index).getIdMesto();
        }

        AMKlub amk = new AMKlub(id, naziv, telefon, mejl, mestoID);

        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.AZURIRAJ_AMK, amk);
        Komunikacija.getInstance().posalji_zahtev(kz);
        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        if (so == null) {
            JOptionPane.showMessageDialog(this, "Greška u komunikaciji sa serverom!", "GREŠKA!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String odgovor = (String) so.getOdgovor();
        switch (odgovor) {
            case "USPEH!":
                JOptionPane.showMessageDialog(this, "Uspešno ažuriranje podataka o AM klubu!", "USPEH!", JOptionPane.INFORMATION_MESSAGE);
                famk.PRIKAZI_PODATKE_TABELE();
                this.dispose();
                break;
            case "NEPOSTOJI!":
                JOptionPane.showMessageDialog(this, "AM klub koji pokušavate da ažurirate više ne postoji u bazi!", "UPOZORENJE!", JOptionPane.WARNING_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Greška prilikom ažuriranja podataka o AM klubu! \n"
                        + "Proverite konekciju sa BAZOM!", "GREŠKA!", JOptionPane.ERROR_MESSAGE);
                break;
        }

//        postaviPocetnuVrednostCB();
//        
//        int id = Integer.valueOf(jLabelID.getText());
//        String naziv = jTextFieldNAZIV.getText();
//        String telefon = jTextFieldTLEFON.getText();
//        String mejl = jTextFieldEMAIL.getText();
//        mestoID = (int) jComboBoxMESTA.getSelectedItem();
//        
//        AMKlub amk = new AMKlub(id, naziv, telefon, mejl, mestoID);
//        
//        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.AZURIRAJ_AMK, amk);
//        Komunikacija.getInstance().posalji_zahtev(kz);
//        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();
//        
////        if (so == null || so.getOdgovor().equals("NEUSPEH!")) {
////            JOptionPane.showMessageDialog(this, "Greska prilikom azuriranja podataka o AM klubu!", "GRESKA!", JOptionPane.ERROR_MESSAGE);
////        }
////        JOptionPane.showMessageDialog(this, "Uspesno azuriranje podataka o AM klubu!", "USPEH!", JOptionPane.INFORMATION_MESSAGE);
////        famk.PRIKAZI_PODATKE_TABELE();
////        this.dispose();
//
//        if (so == null) {
//            JOptionPane.showMessageDialog(this, "Greška u komunikaciji sa serverom!", "GREŠKA!", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        String odgovor = (String) so.getOdgovor();
//        switch (odgovor) {
//            case "USPEH!":
//                JOptionPane.showMessageDialog(this, "Uspešno ažuriranje podataka o AM klubu!", "USPEH!", JOptionPane.INFORMATION_MESSAGE);
//                famk.PRIKAZI_PODATKE_TABELE();
//                this.dispose();
//                break;
//            case "NEPOSTOJI!":
//                JOptionPane.showMessageDialog(this, "AM klub koji pokušavate da ažurirate više ne postoji u bazi!", "UPOZORENJE!", JOptionPane.WARNING_MESSAGE);
//                break;
//            default:
//                JOptionPane.showMessageDialog(this, "Greška prilikom ažuriranja podataka o AM klubu!", "GREŠKA!", JOptionPane.ERROR_MESSAGE);
//                break;
//        }

    }//GEN-LAST:event_jButtonAZURIRAJActionPerformed

    private void jButtonOBRISIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOBRISIActionPerformed

        int id = Integer.valueOf(jLabelID.getText());

        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.OBRISI_AMK, id);
        Komunikacija.getInstance().posalji_zahtev(kz);
        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        if (so == null) {
            JOptionPane.showMessageDialog(this, "Greška u komunikaciji sa serverom!", "GREŠKA!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String odgovor = (String) so.getOdgovor();
        switch (odgovor) {
            case "USPEH!":
                JOptionPane.showMessageDialog(this, "Uspešno brisanje podataka o AM klubu!", "USPEH!", JOptionPane.INFORMATION_MESSAGE);
                famk.PRIKAZI_PODATKE_TABELE();
                this.dispose();
                break;
            case "NEPOSTOJI!":
                JOptionPane.showMessageDialog(this, "AM Klub nije moguće obrisati \n"
                        + "AM klub koji pokušavate da obrišete još uvek sadrži takmičare u bazi!", "UPOZORENJE!", JOptionPane.WARNING_MESSAGE);
                famk.PRIKAZI_PODATKE_TABELE();
                this.dispose();
                break;
            default:
                JOptionPane.showMessageDialog(this, "Greška prilikom brisanja podataka o AM klubu!", "GREŠKA!", JOptionPane.ERROR_MESSAGE);
                break;
        }

//        int id = Integer.valueOf(jLabelID.getText());
//        
//        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.OBRISI_AMK, id);
//        Komunikacija.getInstance().posalji_zahtev(kz);
//        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();
//        
//        if (so == null || so.getOdgovor().equals("NEUSPEH!")) {
//            JOptionPane.showMessageDialog(this, "Greska prilikom brisanja podataka o AM klubu!", "GRESKA!", JOptionPane.ERROR_MESSAGE);
//        }
//        JOptionPane.showMessageDialog(this, "Uspesno brisanje podataka o AM klubu!", "USPEH!", JOptionPane.INFORMATION_MESSAGE);
//        famk.PRIKAZI_PODATKE_TABELE();
//        this.dispose();

    }//GEN-LAST:event_jButtonOBRISIActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAZURIRAJ;
    private javax.swing.JButton jButtonDODAJ;
    private javax.swing.JButton jButtonOBRISI;
    private javax.swing.JComboBox<String> jComboBoxMESTA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JTextField jTextFieldNAZIV;
    private javax.swing.JTextField jTextFieldTLEFON;
    private javax.swing.JLabel lblErrEmail;
    private javax.swing.JLabel lblErrNaziv;
    private javax.swing.JLabel lblErrTelefon;
    // End of variables declaration//GEN-END:variables

    private void pripremiZaNoviUnos_AMK() {

        int IDamk = vrati_id_amk() + 1;
        jLabelID.setText(String.valueOf(IDamk));
        jLabelID.setVisible(false);        ///   ZADNJE DODATO, DA NE KOMPLIKUJEMO I OVAKO VEC KOMPLIKOVANO :/
        jLabel1.setVisible(false);
        
        jTextFieldNAZIV.setText("");
        jTextFieldTLEFON.setText("");
        jTextFieldEMAIL.setText("");

        jButtonDODAJ.setVisible(true);
        jButtonOBRISI.setVisible(false);
        jButtonAZURIRAJ.setVisible(false);
    }

    private void prikaziPodatkeAMK() {

        jLabelID.setText(String.valueOf(amk.getIdAMK()));
        jTextFieldNAZIV.setText(amk.getNazivAMKluba());
        jTextFieldTLEFON.setText(amk.getBrojTelefona());
        jTextFieldEMAIL.setText(amk.getEmailAMK());
    }

    private void popuniCB_mesto() {

        // 
        Klijentski_Zahtev kzM = new Klijentski_Zahtev(Operacije.VRATI_SVA_MESTA, null);
        Komunikacija.getInstance().posalji_zahtev(kzM);
        Serverski_Odgovor soM = Komunikacija.getInstance().primi_odgovor();

        listaMesta = (List<Mesto>) soM.getOdgovor();
        jComboBoxMESTA.removeAllItems();

        //
        for (Mesto mes : listaMesta) {
            jComboBoxMESTA.addItem(mes.getNazivMesto() + " (" + mes.getOpstina() + ")");
        }
        jComboBoxMESTA.setSelectedIndex(-1);

        // 4. Listener za promene tj "lajv apdejt"
        jComboBoxMESTA.addActionListener(e -> {
            int index = jComboBoxMESTA.getSelectedIndex();
            if (index >= 0 && index < listaMesta.size()) {
                mestoID = listaMesta.get(index).getIdMesto();
                System.out.println("Izabrano mestoID: " + mestoID);
            }
        });
    }

    private void postaviPocetnuVrednostCB() {
        if (amk != null && listaMesta != null) {
            for (int i = 0; i < listaMesta.size(); i++) {
                Mesto mes = listaMesta.get(i);
                if (amk.getMestoID() == mes.getIdMesto()) {
                    jComboBoxMESTA.setSelectedIndex(i); // postavi selektovani index
                    mestoID = mes.getIdMesto();
                    return;
                }
            }
        }
    }

//        private void postaviPocetnuVrednostCB() {
//            if (amk != null) {
//                // ako se radi o editovanju postojećeg AMK
//                for (Mesto mes : listaMesta) {
//                    if (amk.getMestoID() == mes.getIdMesto()) {
//                        jComboBoxMESTA.setSelectedItem(mes.getNazivMesto());
//                        mestoID = mes.getIdMesto();
//                        return;
//                    }
//                }
//            } 
//        else {
//            // ako se radi o dodavanju novog AMK → ostavi prazan combo
//            jComboBoxMESTA.setSelectedIndex(-1);
//            mestoID = 0;
//        }
    private void azurirajPodatkeCB_mesto() {

        if (listaMesta == null || listaMesta.isEmpty()) {
            return;
        }

        String izabranoMesto = (String) jComboBoxMESTA.getSelectedItem();
        if (izabranoMesto == null) {
            return;
        }

        for (Mesto mesto : listaMesta) {
            if (mesto.getNazivMesto().equals(izabranoMesto)) {
                mestoID = mesto.getIdMesto();
                return;
            }
        }

    }

    private int vrati_id_amk() {

        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.VRATI_NAJVECI_ID_AMK, null);
        Komunikacija.getInstance().posalji_zahtev(kz);
        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        int najveciId = 0;
        if (so != null && so.getOdgovor() instanceof Integer) {
            najveciId = (Integer) so.getOdgovor();
        }
        //System.out.println("Najveći ID amk: " + najveciId);
        return najveciId;
    }
}
