/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

//import controller.Controller;
import controlerUI.ValidatorUI;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import komunikacija.Komunikacija;
import model.CVM;
import operacije.Operacije;
//import pomocne.Pomocne;
import transfer.Klijentski_Zahtev;
import transfer.Serverski_Odgovor;

/**
 *
 * @author Srecko
 */
public class Forma_za_prijavu extends javax.swing.JFrame {

    /**
     * Creates new form Forma_za_prijavu
     */
    public Forma_za_prijavu() {
        initComponents();
        setLocationRelativeTo(null);

        this.SAKRI.setVisible(false);

        ValidatorUI.validateEmail(jTextFieldEMAIL, lblErrorEmail);
        ValidatorUI.validateLozinka(jPasswordField1, lblErrorLozinka);

        ValidatorUI.enableAutoButtonControl(
                jButtonPRIJAVI_SE,
                new JTextField[]{jTextFieldEMAIL, jPasswordField1},
                new JComboBox[]{} // nema combo boxeva
        );
        ValidatorUI.updateButtonState(jButtonPRIJAVI_SE,
                new JTextField[]{jTextFieldEMAIL, jPasswordField1},
                new JComboBox[]{});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEMAIL = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButtonPRIJAVI_SE = new javax.swing.JButton();
        jButtonREGISTRUJ_SE = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PRIKAZI = new javax.swing.JLabel();
        SAKRI = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorLozinka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRIJAVA");

        jLabel2.setText("E-mail adresa:");

        jLabel3.setText("Lozinka:");

        jTextFieldEMAIL.setText("CVMBG@gmail.com");
        jTextFieldEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEMAILActionPerformed(evt);
            }
        });

        jPasswordField1.setText("cvm123");

        jButtonPRIJAVI_SE.setText("PRIJAVI SE");
        jButtonPRIJAVI_SE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPRIJAVI_SEActionPerformed(evt);
            }
        });

        jButtonREGISTRUJ_SE.setText("REGISTRUJ SE");
        jButtonREGISTRUJ_SE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonREGISTRUJ_SEActionPerformed(evt);
            }
        });

        jLabel4.setText("Zelite li da napravite nalog?");

        PRIKAZI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/eye.png"))); // NOI18N
        PRIKAZI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PRIKAZIMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PRIKAZIMousePressed(evt);
            }
        });

        SAKRI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/forme/eye_hide.png"))); // NOI18N
        SAKRI.setPreferredSize(new java.awt.Dimension(30, 30));
        SAKRI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SAKRIMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jButtonPRIJAVI_SE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonREGISTRUJ_SE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblErrorEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEMAIL, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorLozinka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPasswordField1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PRIKAZI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAKRI, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(jTextFieldEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(lblErrorEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3))
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAKRI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PRIKAZI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorLozinka)
                .addGap(80, 80, 80)
                .addComponent(jButtonPRIJAVI_SE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(jButtonREGISTRUJ_SE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPRIJAVI_SEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPRIJAVI_SEActionPerformed

        String email = jTextFieldEMAIL.getText();
        String lozinka = String.valueOf(jPasswordField1.getPassword());

        CVM cvm = new CVM();
        cvm.setEmail(email);
        cvm.setLozinka(lozinka);

        // Slanje zahteva za prijavu
        Klijentski_Zahtev kz = new Klijentski_Zahtev(Operacije.PRIJAVA, cvm);
        Komunikacija.getInstance().posalji_zahtev(kz);

        // odgovor sa servera
        Serverski_Odgovor so = Komunikacija.getInstance().primi_odgovor();

        if (so.getOdgovor() instanceof String && so.getOdgovor().equals("NEUSPEH!")) {
            JOptionPane.showMessageDialog(this, "Pogrešni kredencijali!", "Greška!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (so.getOdgovor() instanceof CVM) {
            CVM prijavljen = (CVM) so.getOdgovor();
            JOptionPane.showMessageDialog(this, "Dobrodošao " + prijavljen.getNazivCVM(), "Uspeh!", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();
            Glavna_forma gf = new Glavna_forma(prijavljen); // sada prosleđuje ceo objekat
            gf.setVisible(true);
        } 
        else {
            JOptionPane.showMessageDialog(this, "Desila se greska pri prijavljivanju na sistem, probajte ponovo!\n"
                    + "Takodje proverite konekciju sa SERVEROM!", "GRESKA", JOptionPane.ERROR_MESSAGE);
        }
        /*  // Slanje zahteva za dobijanje naziva CVM-a
        kz = new Klijentski_Zahtev(Operacije.VRATI_NAZIV_CVM, cvm);
        Komunikacija.getInstance().posalji_zahtev(kz);
        so = Komunikacija.getInstance().primi_odgovor();

        if (so != null && !so.getOdgovor().equals("NEUSPEH!")) {
            String nazivCVM = (String) so.getOdgovor();

            this.dispose();
            Glavna_forma gf = new Glavna_forma(nazivCVM, email, lozinka);
            gf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Greska prilikom dobijanja naziva CVM-a", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
         */
//        boolean prijavljeni = Controller.getInstance().login(email, lozinka);
//
//        if (!prijavljeni) {
//            JOptionPane.showMessageDialog(this, "Pogresni kredencijali! Pokusajte ponovo", "Greska!", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//        JOptionPane.showMessageDialog(this, "Uspesno prijavljivanje", "Uspeh!", JOptionPane.INFORMATION_MESSAGE);
//
//        String nazivCVM = Controller.getInstance().vrati_naziv_CVM(email, lozinka);
//        
//        this.dispose();
//        Glavna_forma gf = new Glavna_forma(nazivCVM, email, lozinka);
//        gf.setVisible(true);

    }//GEN-LAST:event_jButtonPRIJAVI_SEActionPerformed

    private void jTextFieldEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEMAILActionPerformed

    private void jButtonREGISTRUJ_SEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonREGISTRUJ_SEActionPerformed

        Forma_za_registraciju fzr = new Forma_za_registraciju();
        fzr.setVisible(true);
    }//GEN-LAST:event_jButtonREGISTRUJ_SEActionPerformed

    private void PRIKAZIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRIKAZIMouseClicked


    }//GEN-LAST:event_PRIKAZIMouseClicked

    private void PRIKAZIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PRIKAZIMousePressed

        SAKRI.setVisible(true);
        PRIKAZI.setVisible(false);
        String lozinka = String.valueOf(jPasswordField1.getPassword());

        jPasswordField1.setEchoChar((char) 0);
    }//GEN-LAST:event_PRIKAZIMousePressed

    private void SAKRIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SAKRIMousePressed

        SAKRI.setVisible(false);
        PRIKAZI.setVisible(true);
        String lozinka = String.valueOf(jPasswordField1.getPassword());

        jPasswordField1.setEchoChar('*');
    }//GEN-LAST:event_SAKRIMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forma_za_prijavu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forma_za_prijavu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forma_za_prijavu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forma_za_prijavu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forma_za_prijavu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PRIKAZI;
    private javax.swing.JLabel SAKRI;
    private javax.swing.JButton jButtonPRIJAVI_SE;
    private javax.swing.JButton jButtonREGISTRUJ_SE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldEMAIL;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorLozinka;
    // End of variables declaration//GEN-END:variables
}
