/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

//import controller.Controller;
//import com.mysql.cj.util.Util;
import controlerUI.DatabaseConnectionMonitor;
import controlerUI.ThemeManager;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import komunikacija.Komunikacija;
import model.CVM;
import niti.Osvezi_Tabele;
import operacije.Operacije;
import transfer.Klijentski_Zahtev;
import transfer.Serverski_Odgovor;
//import util.ThemeManager;

/**
 *
 * @author Srecko
 */
public class Glavna_forma extends javax.swing.JFrame {

    Forma_za_prijavu fzp = new Forma_za_prijavu();

    private String nazivCVM;
    private String email;
    private String lozinka;
    private CVM prijavljen;

    Osvezi_Tabele nit;

    /**
     * Creates new form Glavna_forma
     */
    // NISAM MORAO NAZIV DA PROSLEDJUJEM ALI NMVZ
    public Glavna_forma(CVM prijavljen) {
        this.prijavljen = prijavljen;
        initComponents();
        setLocationRelativeTo(null);

        
        //////////////////////////////////////
        //===============================
        //        DatabaseConnectionMonitor monitor = new DatabaseConnectionMonitor();
        //        monitor.start();

        controlerUI.ThemeManager.applyTheme(this);

        popuniFormu();

        Osvezi_Tabele.dodajZadatak(() -> popuniFormu());
        Osvezi_Tabele.pokreni();

        prikaziTrenutniDatumIVreme(jLabel_DatumVreme);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCVM = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelLICENCA = new javax.swing.JLabel();
        jLabelBR_TEL = new javax.swing.JLabel();
        jLabelEMAIL = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOstaliCVM = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButtonDetaljneInformacije = new javax.swing.JButton();
        jButton_MODE = new javax.swing.JButton();
        jLabel_DatumVreme = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAMKLUBOVI = new javax.swing.JMenuItem();
        jMenuItemTAKMICENJA = new javax.swing.JMenuItem();
        jMenuItemTAKMICARI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Početna Stranica");

        jLabelCVM.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelCVM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Osnovne invormacije: ");

        jLabel2.setText("Licenca: ");

        jLabel3.setText("Broj telefona:");

        jLabel4.setText("Email: ");

        jLabelLICENCA.setText("jLabel5");

        jLabelBR_TEL.setText("jLabel5");

        jLabelEMAIL.setText("jLabel5");

        jTableOstaliCVM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableOstaliCVM);

        jLabel5.setText("Osnovne infomacije o ostalim Centrima za Vazduhoplovno Modelarstvo");

        jButtonDetaljneInformacije.setText("Detaljne informacije");
        jButtonDetaljneInformacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljneInformacijeActionPerformed(evt);
            }
        });

        jButton_MODE.setText("🌙 Dark Mode");
        jButton_MODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MODEActionPerformed(evt);
            }
        });

        jLabel_DatumVreme.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel_DatumVreme.setPreferredSize(new java.awt.Dimension(38, 26));

        jMenu1.setText("Meni");

        jMenuItemAMKLUBOVI.setText("AM Klubovi");
        jMenuItemAMKLUBOVI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAMKLUBOVIActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAMKLUBOVI);

        jMenuItemTAKMICENJA.setText("Takmicenja");
        jMenuItemTAKMICENJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTAKMICENJAActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTAKMICENJA);

        jMenuItemTAKMICARI.setText("Takmicari");
        jMenuItemTAKMICARI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTAKMICARIActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemTAKMICARI);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCVM)
                        .addContainerGap(1347, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(92, 92, 92)
                                .addComponent(jLabelLICENCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(68, 68, 68)
                                .addComponent(jLabelBR_TEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(103, 103, 103)
                                .addComponent(jLabelEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButtonDetaljneInformacije)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel_DatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_MODE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_DatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_MODE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCVM)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelLICENCA)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelBR_TEL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelEMAIL))
                        .addGap(36, 36, 36)
                        .addComponent(jButtonDetaljneInformacije))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(257, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetaljneInformacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljneInformacijeActionPerformed

        Forma_za_podatke_o_CVM fzp = new Forma_za_podatke_o_CVM(prijavljen, this);
        fzp.setVisible(true);
    }//GEN-LAST:event_jButtonDetaljneInformacijeActionPerformed

    private void jMenuItemTAKMICENJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTAKMICENJAActionPerformed
        Forma_TAKMICENJE fp = new Forma_TAKMICENJE(prijavljen);
        fp.setVisible(true);
    }//GEN-LAST:event_jMenuItemTAKMICENJAActionPerformed

    private void jMenuItemTAKMICARIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTAKMICARIActionPerformed
        Forma_Takmicari ft = new Forma_Takmicari();
        ft.setVisible(true);
    }//GEN-LAST:event_jMenuItemTAKMICARIActionPerformed

    private void jMenuItemAMKLUBOVIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAMKLUBOVIActionPerformed
        Forma_AM_Klubovi famk = new Forma_AM_Klubovi();
        famk.setVisible(true);
    }//GEN-LAST:event_jMenuItemAMKLUBOVIActionPerformed

    private void jButton_MODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MODEActionPerformed
        ThemeManager.toggleTheme();

        if (ThemeManager.isDarkMode()) {
            jButton_MODE.setText("☀️ Light Mode");
            jButton_MODE.setBackground(new java.awt.Color(70, 70, 70));
            jButton_MODE.setForeground(new java.awt.Color(230, 230, 230));
        } else {
            jButton_MODE.setText("🌙 Dark Mode");
            jButton_MODE.setBackground(java.awt.Color.WHITE);
            jButton_MODE.setForeground(java.awt.Color.BLACK);
        }

//        // 🔁 Prebaci temu (dark <-> light)
//        util.ThemeManager.toggleTheme();
//
//        // 🔄 Osveži tekst i izgled dugmeta
//        if (util.ThemeManager.isDarkMode()) {
//            jButton_MODE.setText("☀️ Light Mode");
//            jButton_MODE.setBackground(new java.awt.Color(70, 70, 70));
//            jButton_MODE.setForeground(new java.awt.Color(230, 230, 230));
//        } else {
//            jButton_MODE.setText("🌙 Dark Mode");
//            jButton_MODE.setBackground(java.awt.Color.WHITE);
//            jButton_MODE.setForeground(java.awt.Color.BLACK);
//        }
    }//GEN-LAST:event_jButton_MODEActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetaljneInformacije;
    private javax.swing.JButton jButton_MODE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBR_TEL;
    private javax.swing.JLabel jLabelCVM;
    private javax.swing.JLabel jLabelEMAIL;
    private javax.swing.JLabel jLabelLICENCA;
    private javax.swing.JLabel jLabel_DatumVreme;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAMKLUBOVI;
    private javax.swing.JMenuItem jMenuItemTAKMICARI;
    private javax.swing.JMenuItem jMenuItemTAKMICENJA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOstaliCVM;
    // End of variables declaration//GEN-END:variables

    public void popuniFormu() {

        try {

            Klijentski_Zahtev kzDetalji = new Klijentski_Zahtev(Operacije.VRATI_CVM_DETALJE, prijavljen);
            Komunikacija.getInstance().posalji_zahtev(kzDetalji);
            Serverski_Odgovor soDetalji = Komunikacija.getInstance().primi_odgovor();

            if (soDetalji != null && soDetalji.getOdgovor() instanceof CVM) {
                this.prijavljen = (CVM) soDetalji.getOdgovor(); // ažuriraj objekat
            }

            jLabelCVM.setText(prijavljen.getNazivCVM());
            jLabelLICENCA.setText(prijavljen.getLicenca());
            jLabelBR_TEL.setText(prijavljen.getBr_telefona());
            jLabelEMAIL.setText(prijavljen.getEmail());

            //tabela       
            Klijentski_Zahtev kzSvi = new Klijentski_Zahtev(Operacije.VRATI_SVE_CVM, null);
            Komunikacija.getInstance().posalji_zahtev(kzSvi);
            Serverski_Odgovor soSvi = Komunikacija.getInstance().primi_odgovor();

            if (soSvi != null && soSvi.getOdgovor() instanceof List) {
                List<CVM> sviCVM = (List<CVM>) soSvi.getOdgovor();

                // Ukloni trenutno prijavljenog iz liste 
                //sviCVM.removeIf(c -> c.getIdCVM() == prijavljen.getIdCVM());
                jTableOstaliCVM.setModel(new Model_Tabele_OstaliCVM(sviCVM));
            } else {
                JOptionPane.showMessageDialog(this,
                        "Greška prilikom učitavanja liste CVM-ova.",
                        "Greška", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Greška prilikom učitavanja podataka: " + e.getMessage(),
                    "Greška", JOptionPane.ERROR_MESSAGE);
        }

        //        List<CVM> podaciCVM = new ArrayList<>();
//
//        CVM cvm = new CVM();
//        cvm.setEmail(prijavljen.getEmail());
//        cvm.setLozinka(prijavljen.getLozinka());
//
//        jLabelCVM.setText(prijavljen.getNazivCVM());
//        jLabelLICENCA.setText(prijavljen.getLicenca());
//        jLabelBR_TEL.setText(prijavljen.getBr_telefona());
//        jLabelEMAIL.setText(prijavljen.getEmail());
//
//        Klijentski_Zahtev kz;
//        Serverski_Odgovor so;
//
//        // SETOVANJE TABELE ZA PRIKAZ OSTALIH CVM-A
//        List<CVM> ostaliCVM = new ArrayList<>();
//        // Slanje zahteva za dobijanje svih CVM-a
//        kz = new Klijentski_Zahtev(Operacije.VRATI_SVE_CVM, null);
//        Komunikacija.getInstance().posalji_zahtev(kz);
//        so = Komunikacija.getInstance().primi_odgovor();
//
//        if (so != null && !so.getOdgovor().equals("NEUSPEH!")) {
//            ostaliCVM = (List<CVM>) so.getOdgovor();
//        } else {
//            JOptionPane.showMessageDialog(this, "Greska prilikom dobijanja ostalih CVM-a", "Greska!", JOptionPane.ERROR_MESSAGE);
//        }
//
//        Model_Tabele_OstaliCVM mto = new Model_Tabele_OstaliCVM(ostaliCVM);
//        jTableOstaliCVM.setModel(mto);
    }

    private void prikaziTrenutniDatumIVreme(JLabel label) {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy. HH:mm:ss");

        Timer timer = new Timer(1000, e -> {
            label.setText(sdf.format(new Date()));
        });
        timer.start();
    }

}
